### ISSUE TITLE
SAGE - Vorabveröffentlichung evtl. nicht immer zulässig?

### ISSUE THREAD

**Issue by Igor-Hammer** [tuub/theses-publisher-policies#3]
Hallo,
erst mal vielen vielen Dank für die sooo nützliche Seite - die ist sehr hilfreich!

Bei SAGE bin ich mir nicht sicher, ob Vorabveröffentlichungen immer zulässig sind, wie es in der Tabelle heisst. Im ersten Abschnitt unter "Green Open Access: SAGE’s Archiving and Sharing Policy" auf https://uk.sagepub.com/en-gb/eur/journal-author-archiving-policies-and-re-use heisst es "Please note some journals will not consider papers that have been posted as preprints prior to submission" - wäre das daher nicht eher ein "zulässig mit Ausnahmen"?

Herzliche Grüsse

Igor Hammer

**Comment by michaelavoigt** [comment]
Danke für den Hinweis. Dürfte nur wenige Journale betreffen, aber dennoch relevante Info. Eintrag in Tab. ist angepasst ([vgl.](https://github.com/tuub/theses-publisher-policies/commit/44f0bb35e7b32504ba661612ed130e9f62dbaff8)) und auch Link zu ["Prior Publication" Policy](https://uk.sagepub.com/en-gb/eur/prior-publication) ergänzt
