### ISSUE TITLE
Springer: neu keine Genehmigung vom Verlag mehr nötig?

### ISSUE THREAD

**Issue by Igor-Hammer** [tuub/theses-publisher-policies#4]
Hallo,
nochmals ich :-)
Kürzlich haben wir vom Verlag die unten angehängte E-Mail erhalten. Das tönt ja nach einer Kehrtwende, da Springer vorher immer darauf bestanden hat, dass man auch bei einer eigentlich erlaubten Nutzung immer eine Genehmigung des Verlags einholen musste. 
Haben Sie dazu Informationen, ob das die neue allgemeine Policy von Springer ist? oder sollen wir sicherheitshalber doch immer noch eine Bestätigung verlangen lassen von unseren Dissertierenden?
Beste Grüsse
Igor Hammer

Betreff: | RE: Copyright inquiry for dissertation
-- | --
Datum: | Wed, 17   Jun 2020 08:23:34 +0000
Von: | Journalpermissions <journalpermissions@springernature.com>
An: | Stefan   Weber <stefan.weber@students.unibe.ch>

Dear Stefan, 
Thank you for your Springer Nature permissions query. Our authors retain the right to use their article to  further their scientific career by including the final published journal article in other publications such as dissertations and postdoctoral qualifications provided acknowledgement is given to the original source of publication. 
You do not need permission to reuse your article in a thesis/dissertation. 
Best wishes,
Oda 
Oda Siqveland
Rights Executive 
SpringerNature
The Campus, 4 Crinan Street, London N1 9XW,
United Kingdom
T   +44 (0) 207 014 6851
http://www.nature.com
http://www.springer.com
http://www.palgrave.com

**Comment by michaelavoigt** [comment]
Lieber @Igor-Hammer 
Danke für den Hinweis, diese Änderung war uns auch neu - aber schön. Wir haben hier noch mal nachgehakt beim Verlag (separat für Bücher + Artikel) und sie haben Hinweis unter https://www.springer.com/gp/rights-permissions/obtaining-permissions/882 bestätigt; allerdings keine Aussage zu Preprint/ akzeptiertes Manuscript getroffen - leider. Die Angaben in der Tabelle sind entsprechend aktualisiert (vgl. https://github.com/tuub/theses-publisher-policies/commit/65e134fabf4d0afa780a0cf26652cc2fde9579f1)
Danke für den Hinweis!
