### ISSUE TITLE
Nature: Version of Record immer erlaubt?

### ISSUE THREAD

**Issue by Igor-Hammer** [tuub/theses-publisher-policies#7]
Guten Tag,
Auf der Seite https://www.nature.com/nature-portfolio/reprints-and-permissions/permissions-requests des Nature-Verlags habe ich folgende Information gefunden: 

Author reuse
Authors have the right to reuse their article’s Version of Record, in whole or in part, in their own thesis. Additionally, they may reproduce and make available their thesis, including Springer Nature content, as required by their awarding academic institution.

Interpretiere ich das richtig, dass unsere Dissertierenden die publizierte Version Ihres Artikels ohne Embargofrist in die Dissertation einfügen dürfen und wir die Dissertation Open Access publizieren dürfen, wenn die Institutsregeln dies so vorsehen? 
Dies wäre ein etwas überraschende Möglichkeit, das 6-Monats-Embargo für die Publikation des Accepted Manuscripts zu umgehen...

Beste Grüsse

Igor Hammer

**Comment by michaelavoigt** [comment]
Danke @Igor-Hammer für den Hinweis! wir lesen es so wie Sie und haben Eintrag aktualisiert... gilt jetzt also wohl generell bei Springer UND Nature, das VoR genutzt werden kann in Diss - auch bei Onlineveröffentlichung.

**Comment by michaelavoigt** [comment]
entry updated (cf. https://github.com/tuub/theses-publisher-policies/commit/868c74f17f90da4d2c6f2bc166f297e5c5c8c675)
